name: Automation Testing with Postman CLI

on:
  push:
    branches: [ "main", "master", "develop" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run-postman-tests:
    runs-on: ubuntu-latest

    steps:
    # 1. Kéo code từ GitHub về máy ảo
    - name: Checkout repository
      uses: actions/checkout@v4

    # 2. Cài đặt Postman CLI trên máy ảo GitHub
    - name: Install Postman CLI
      run: |
        curl -o- "https://dl-cli.pstmn.io/install/linux64.sh" | sh

    # 3. Đăng nhập vào Postman CLI bằng API Key lấy từ Secrets
    - name: Login to Postman CLI
      run: |
        postman login --with-api-key ${{ secrets.POSTMAN_API_KEY }}

    # 4. Tiến hành chạy test tự động bằng Collection ID lấy từ Secrets
    - name: Run Postman Collection
      run: |
        postman collection run ${{ secrets.POSTMAN_COLLECTION_ID }}

    # 5. Đăng nhập vào Jira (Sửa lại chuẩn biến để sinh file config.yml)
    - name: Login to Jira
      if: failure()
      uses: atlassian/gajira-login@v3
      env:
        atlassian_host: 'https://ktpm-uth.atlassian.net'
        user_email: ${{ secrets.JIRA_USER }}
        api_token: ${{ secrets.JIRA_TOKEN }}

    # 6. Tạo Bug và Assign lên Jira sau khi đã login thành công
    - name: Create Jira Bug on Failure
      if: failure()
      uses: atlassian/gajira-create@v3
      with:
        project: 'KAN'
        issuetype: 'Bug'
        summary: '🔴 [Automation Test] Phát hiện lỗi API khi chạy Automation Test Pipeline'
        description: |
          Hệ thống kiểm thử tự động phát hiện có API bị lỗi.
          Vui lòng kiểm tra lại log chi tiết trên GitHub Actions.
          Luồng kiểm thử: Postman CLI.
        fields: '{"assignee": {"id": "712020:0bd697e4-f5b4-4767-b9f5-fae031ed3398"}}'